-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 18:26:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabalhofinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalhofinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalhofinal` DEFAULT CHARACTER SET utf8 ;
USE `trabalhofinal` ;

-- -----------------------------------------------------
-- Table `trabalhofinal`.`Salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Salas` (
  `ID_Sala` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Computadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Computadores` (
  `ID_Computador` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Numero` TINYINT(2) UNSIGNED NOT NULL,
  `ID_Sala` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Computador`),
  INDEX `fk_Computadores_Salas_idx` (`ID_Sala` ASC),
  CONSTRAINT `fk_Computadores_Salas`
    FOREIGN KEY (`ID_Sala`)
    REFERENCES `trabalhofinal`.`Salas` (`ID_Sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Usuarios` (
  `ID_Usuario` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(140) NOT NULL,
  `Senha` VARCHAR(20) NOT NULL,
  `isAdministrador` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID_Usuario`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Problemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Problemas` (
  `ID_Problema` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  `Tipo` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Problema`),
  UNIQUE INDEX `Descricao_UNIQUE` (`Descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Chamados` (
  `ID_Chamado` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Usuario` TINYINT(3) UNSIGNED NOT NULL,
  `ID_Usuario_Administrador` TINYINT(3) UNSIGNED NULL,
  `Data_Inicial` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Data_Final` DATETIME NULL,
  `ID_Computador` SMALLINT(4) UNSIGNED NOT NULL,
  `ID_Problema` TINYINT(1) UNSIGNED NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  `Status` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Chamado`),
  INDEX `fk_Chamadas_Usuarios1_idx` (`ID_Usuario` ASC),
  INDEX `fk_Chamadas_Usuarios2_idx` (`ID_Usuario_Administrador` ASC),
  INDEX `fk_Chamadas_Computadores1_idx` (`ID_Computador` ASC),
  INDEX `fk_Chamadas_Problemas1_idx` (`ID_Problema` ASC),
  CONSTRAINT `fk_Chamadas_Usuarios1`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `trabalhofinal`.`Usuarios` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chamadas_Usuarios2`
    FOREIGN KEY (`ID_Usuario_Administrador`)
    REFERENCES `trabalhofinal`.`Usuarios` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chamadas_Computadores1`
    FOREIGN KEY (`ID_Computador`)
    REFERENCES `trabalhofinal`.`Computadores` (`ID_Computador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chamadas_Problemas1`
    FOREIGN KEY (`ID_Problema`)
    REFERENCES `trabalhofinal`.`Problemas` (`ID_Problema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `trabalhofinal`.`Salas`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabalhofinal`;
INSERT INTO `trabalhofinal`.`Salas` (`ID_Sala`) VALUES (101);
INSERT INTO `trabalhofinal`.`Salas` (`ID_Sala`) VALUES (202);
INSERT INTO `trabalhofinal`.`Salas` (`ID_Sala`) VALUES (303);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabalhofinal`.`Computadores`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabalhofinal`;
INSERT INTO `trabalhofinal`.`Computadores` (`ID_Computador`, `Numero`, `ID_Sala`) VALUES (1, 1, 101);
INSERT INTO `trabalhofinal`.`Computadores` (`ID_Computador`, `Numero`, `ID_Sala`) VALUES (2, 1, 202);
INSERT INTO `trabalhofinal`.`Computadores` (`ID_Computador`, `Numero`, `ID_Sala`) VALUES (3, 1, 303);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabalhofinal`.`Usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabalhofinal`;
INSERT INTO `trabalhofinal`.`Usuarios` (`ID_Usuario`, `Nome`, `Email`, `Senha`, `isAdministrador`) VALUES (1, 'João', 'joaophickmann@outlook.com', '123456', 0);
INSERT INTO `trabalhofinal`.`Usuarios` (`ID_Usuario`, `Nome`, `Email`, `Senha`, `isAdministrador`) VALUES (2, 'Gordo da TI', 'bacon@carne.com', 'coxinha', 1);
INSERT INTO `trabalhofinal`.`Usuarios` (`ID_Usuario`, `Nome`, `Email`, `Senha`, `isAdministrador`) VALUES (3, 'Guilherme', 'guikipper1@gmail.com', 'sougay', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabalhofinal`.`Problemas`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabalhofinal`;
INSERT INTO `trabalhofinal`.`Problemas` (`ID_Problema`, `Descricao`, `Tipo`) VALUES (1, 'Mouse', 1);
INSERT INTO `trabalhofinal`.`Problemas` (`ID_Problema`, `Descricao`, `Tipo`) VALUES (2, 'Netbeans', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabalhofinal`.`Chamados`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabalhofinal`;
INSERT INTO `trabalhofinal`.`Chamados` (`ID_Chamado`, `ID_Usuario`, `ID_Usuario_Administrador`, `Data_Inicial`, `Data_Final`, `ID_Computador`, `ID_Problema`, `Observacao`, `Status`) VALUES (1, 1, 2, DEFAULT, '01/11/2017', 1, 1, 'Sem Mouse', 3);
INSERT INTO `trabalhofinal`.`Chamados` (`ID_Chamado`, `ID_Usuario`, `ID_Usuario_Administrador`, `Data_Inicial`, `Data_Final`, `ID_Computador`, `ID_Problema`, `Observacao`, `Status`) VALUES (2, 3, NULL, DEFAULT, NULL, 2, 2, 'Não Abre', 1);

COMMIT;

